# Generated by Django 2.2 on 2019-04-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen_Producto')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Category', verbose_name='Categoria'),
        ),
    ]
