# Generated by Django 2.2 on 2019-04-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190408_2220'),
        ('productos', '0003_auto_20190408_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Estado_Factura')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Client', verbose_name='CLiente')),
            ],
        ),
    ]
