# Generated by Django 2.2 on 2019-04-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
