# Generated by Django 2.2 on 2019-04-09 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20190408_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
