# Generated by Django 2.2 on 2019-04-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190408_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Product', verbose_name='Producto')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Bill', verbose_name='Factura')),
            ],
        ),
    ]
