# Generated by Django 2.2 on 2019-04-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria'},
        ),
    ]
