# Generated by Django 2.2 on 2019-04-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20190411_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Categoria'},
        ),
    ]
