# Generated by Django 2.2 on 2019-04-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20190411_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Productos'},
        ),
    ]
