# Generated by Django 2.2 on 2019-04-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20190411_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name_plural': 'Detalles'},
        ),
    ]
