# Generated by Django 2.2 on 2019-04-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20190411_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
