# Generated by Django 2.2 on 2019-04-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20190408_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
